version: "3.7"
services:
  simulator-server:
    image: simulator-server
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://127.0.0.1:2379
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=3131
    ports:
      - "1212:1212"
      - "1313:1313"
      - "3131:3131"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
    volumes:
      - ./kwok.yaml:/.kwok/kwok.yaml
  simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1313
    ports:
    - "3000:3000"
    tty: true
networks:
  simulator-internal-network:
    driver: bridge
